<?php
/**
 * @file
 * DrupalCamp 2015 routeplanner specific stuff.
 */

/**
 * Implements hook_block_info().
 */
function drupalcamp_routeplanner_block_info() {
  $blocks['delijn'] = array(
    'info' => t('Include the routeplanner.'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function drupalcamp_routeplanner_block_view($delta = '') {
  $callback = _drupalcamp_routeplanner_block_callback($delta, 'view');
  if ($callback) {
    return $callback();
  }
}

/**
 * Helper to include the blocks include and to create the proper callback.
 *
 * @param string $delta
 *   The delta of the block.
 * @param string $type
 *   The block hook name (configure, save, view).
 *
 * @return FALSE|string
 *   The callback name will only be returned if it exists.
 */
function _drupalcamp_routeplanner_block_callback($delta, $type) {
  module_load_include(
    'inc',
    'drupalcamp_routeplanner',
    'drupalcamp_routeplanner.blocks'
  );

  $callback = '_drupalcamp_routeplanner_' . $delta . '_' . $type;
  if (!function_exists($callback)) {
    return FALSE;
  }

  return $callback;
}

/**
 * Implements hook_theme().
 */
function drupalcamp_routeplanner_theme($existing, $type, $theme, $path) {
  return array(
    'drupalcamp_routeplanner_delijn_html' => array(
      'template' => 'templates/block--drupalcamp-routeplanner--delijn',
      'arguments' => array(),
    ),
  );
}
