<?php
/**
 * @file
 * Code for the DrupalCamp Belgium Speakers feature.
 */

include_once 'drupalcamp_speaker.features.inc';

/**
 * Implements hook_block_info().
 */
function drupalcamp_speaker_block_info() {
  $blocks['propose'] = array(
    'info' => t('Add "Propose a session" CTA.'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function drupalcamp_speaker_block_view($delta = '') {
  $callback = _drupalcamp_speaker_block_callback($delta, 'view');
  if ($callback) {
    return $callback();
  }
}

/**
 * Helper to include the blocks include and to create the proper callback.
 *
 * @param string $delta
 *   The delta of the block.
 * @param string $type
 *   The block hook name (configure, save, view).
 *
 * @return FALSE|string
 *   The callback name will only be returned if it exists.
 */
function _drupalcamp_speaker_block_callback($delta, $type) {
  module_load_include(
    'inc',
    'drupalcamp_speaker',
    'drupalcamp_speaker.blocks'
  );

  $callback = '_drupalcamp_speaker_' . $delta . '_' . $type;
  if (!function_exists($callback)) {
    return FALSE;
  }

  return $callback;
}
